/*

 HEADSUPDISPLAYMB.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\7319a\Documents\Programming\GameBoy\Projects\retroJam\Assets\Art\GameBoy Tile Designer\GBR Files\Font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define headsUpDisplayMapWidth 20
#define headsUpDisplayMapHeight 2
#define headsUpDisplayMapBank 0

const unsigned char headsUpDisplayMap[] =
{
  0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,
  0x30,0x18,0x1B,0x31,0x14,0x09,0x0D,0x05,0x00,0x1B,
  0x29,0x1B,0x1B,0x00,0x13,0x26,0x1B,0x1B,0x1B,0x1B
};

/* End of HEADSUPDISPLAYMB.C */
