/*

 HEADSUPDISPLAYMB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\7319a\Documents\Programming\GameBoy\Projects\retroJam\Assets\Art\GameBoy Tile Designer\GBR Files\Font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __headsUpDisplayMB_h_INCLUDE
#define __headsUpDisplayMB_h_INCLUDE

#define headsUpDisplayMapWidth 20
#define headsUpDisplayMapHeight 2
#define headsUpDisplayMapBank 0

extern const unsigned char headsUpDisplayMap[];

#endif

/* End of HEADSUPDISPLAYMB.H */
